language: cpp
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      script: make CXX=g++-6 CC=gcc-6
