dist: trusty
script: make -e

matrix:
  include:
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: 
        - CC=gcc-6
        - CXX=g++-6
